# Generated by Django 3.0.3 on 2022-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'scheme',
                'managed': False,
            },
        ),
    ]
