# Generated by Django 3.0.3 on 2022-02-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('userplan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amout', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('cusid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('plid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userplan.Userplan')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
