# Generated by Django 3.0.3 on 2022-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceFixed',
            fields=[
                ('fixed_id', models.AutoField(primary_key=True, serialize=False)),
                ('pamount', models.IntegerField()),
                ('gamount', models.IntegerField()),
            ],
            options={
                'db_table': 'price_fixed',
                'managed': False,
            },
        ),
    ]
