# Generated by Django 3.0.3 on 2022-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixed',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
                ('price4', models.IntegerField()),
                ('price5', models.IntegerField()),
                ('price6', models.IntegerField()),
            ],
            options={
                'db_table': 'fixed',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'package',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('price1', models.CharField(max_length=25)),
                ('price2', models.CharField(max_length=25)),
                ('price3', models.CharField(max_length=25)),
                ('price4', models.CharField(max_length=25)),
                ('price5', models.CharField(max_length=25)),
                ('price6', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'variable',
                'managed': False,
            },
        ),
    ]
