# Generated by Django 3.0.3 on 2022-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('rduration', models.CharField(max_length=25)),
                ('rper', models.CharField(max_length=11)),
                ('type', models.CharField(max_length=11)),
                ('plan', models.CharField(max_length=15)),
                ('rwid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'reward',
                'managed': False,
            },
        ),
    ]
