# Generated by Django 3.0.3 on 2022-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userplan',
            fields=[
                ('plid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('plan', models.CharField(max_length=10)),
                ('payment', models.CharField(max_length=10)),
                ('jdate', models.DateField()),
                ('nddate', models.DateField()),
                ('pcnt', models.IntegerField()),
                ('amt', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'userplan',
                'managed': False,
            },
        ),
    ]
