# Generated by Django 3.0.3 on 2022-02-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountdb',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('acc_no', models.CharField(max_length=25)),
                ('bank', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=10)),
                ('accname', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'accountdb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('pn_id', models.AutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('penalty', models.IntegerField()),
            ],
            options={
                'db_table': 'penalty',
                'managed': False,
            },
        ),
    ]
